#!/bin/bash

NAME=`echo $1|sed 's/:.*//g'|sed 's/.*\///g'`

docker inspect $1 |grep _VERSION|sed 's/.*"\(.*\)".*/\1/g'|sort|uniq|grep -v "GOSU"

VERSION=$(docker run --entrypoint="" $1 rpm -qa --qf "%{NAME} %{VERSION}\n"|grep "$NAME"|sort|head -n 1 2>/dev/null)
if [ $? -eq "0" ]; then
  echo $VERSION
fi
